---

info:
  description: Training configuration repo
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://username:password@service-registry-mwebb.cfapps.io/eureka 
      
corelogic: this is our value
core2: Here is another CIS testing property
